name: Publish on Docker

on:
    # push: 
    #     branches: [ 'main' ]
    workflow_dispatch:

jobs:
    BuildAndTest:
        runs-on: ubuntu-latest
        steps:
            - name: GetRepository
              uses: actions/checkout@v6
            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: '10.0.x'
            - name: Restaurer les packages
              run: dotnet restore
            - id: Build
              name: Build
              run: dotnet build "./WorkerService/WorkerService.csproj" --no-restore -c Release -o ./build
            - id: Tests
              name: Tests
              if: steps.Build.outcome == 'success'
              run: dotnet test --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
            - id: coverage
              if: steps.Tests.outcome == 'success'
              name: Code Coverage Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                filename: Tools.Tests/TestResults/**/coverage.cobertura.xml
                badge: false
                fail_below_min: true        
                hide_branch_rate: false
                hide_complexity: true
                indicators: true
                output: console
                thresholds: '80'
            - name: LoginDocker
              uses: docker/login-action@v3
              with:
                username: ${{vars.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWD}}
            - name: BuildAndPush
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{vars.DOCKER_USERNAME}}/myworkerservice:latest
              

