name: Publish on Docker

on:
    #push: ['main']
    workflow_dispatch:

jobs:
    BuildAndTest:
        runs-on: ubuntu-latest
        steps:
            - name: View Content
              run: ls -l -a
            - name: GetRepository
              uses: actions/checkout@v6
            - name: View Content
              run: ls -l -a
            - name: Build
              run: echo "Build"  
            - name: Tests
              run: echo "Tests"
            

