name: Publish on Docker

on:
    # push: 
    #     branches: [ 'main' ]
    workflow_dispatch:

jobs:
    BuildAndTest:
        runs-on: ubuntu-latest
        steps:
            - name: GetRepository
              uses: actions/checkout@v6
            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: '10.0.x'
            - name: Restaurer les packages
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore  
            - name: Tests
              run: echo "Tests"
            

